### PR TITLE
lua refresh compatibility

### PR DESCRIPTION
**Pull request by Aws0mee**
Tables will get reset with a lua refresh, this will ensure they work even after a lua refresh.

### CODE REVIEW

**Comment by robotboy655** [comment]
But is this an actual issue though? The table will be (re)generated in the iterator functions before they are actually used.

**Comment by Aws0mee** [comment]
> But is this an actual issue though? The table will be (re)generated in the iterator functions before they are actually used.

I was doing some testing and it did appear to be an issue for me. It got fixed pretty quickly, but I thought it just makes sense since the first time it gets loaded there will likely be very few entities so it won't have any performance impact.

**Comment by Aws0mee** [comment]
Unrelated, but I appreciate the work you have been doing on this addon. It's nice to see even after a decade the addon is still getting improved.

**Comment by robotboy655** [comment]
> I was doing some testing and it did appear to be an issue for me.

In what way exactly?

**Comment by Aws0mee** [comment]
> > I was doing some testing and it did appear to be an issue for me.
> 
> In what way exactly?

The lightsabers didn't have their effect on them.

**Comment by robotboy655** [comment]
I cannot reproduce any issues of missing effects after an auto refresh, I tried the weapon file, I tried the 2 autorun files, singleplayer and local multiplayer.

And it doesn't make sense either that effects would go away, because again, those tables would be regenerated before they are used, so they are never actually `nil`, auto refresh or not.

**Comment by Aws0mee** [comment]
> I cannot reproduce any issues of missing effects after an auto refresh, I tried the weapon file, I tried the 2 autorun files, singleplayer and local multiplayer.
> 
> And it doesn't make sense either that effects would go away, because again, those tables would be regenerated before they are used, so they are never actually `nil`, auto refresh or not.

Odd, I thought logically this would be an issue, and I did some testing and I thought it was. Also, wouldn't it be more efficient to check if the entity being created/removed is a lightsaber and then add it to the table instead of calling ents.FindByClass to regenerate it each time?

**Comment by Aws0mee** [comment]
I'd be happy to implement and test this if you want. Also, it would make this PR required as well to work.

**Comment by robotboy655** [comment]
I am not sure that would be reliable, and the way I have it done right now is, as well as provides testing grounds for upcoming GMod feature - https://wiki.facepunch.com/gmod/ents.Iterator

**Comment by Aws0mee** [comment]
> I am not sure that would be reliable, and the way I have it done right now is, as well as provides testing grounds for upcoming GMod feature - https://wiki.facepunch.com/gmod/ents.Iterator

Interesting new feature. Wouldn't it still be faster to create a table initialized to all of the lightsaber entities, then remove/add when a lightsaber entity is removed/added? That way you won't need to iterate over every single entity using ents.Iterator. Also If you don't mind me asking, what are you concerned about with reliability? I have done this before in other addons to improve performance and never seen any issues.

**Comment by robotboy655** [comment]
It technically might be marginally faster, but the biggest performance concern in this case would be iterating over all entities every frame, which is no longer the case.

The reliability concern comes with me not being sure the OnEntityCreated/Removed hooks having the correct class name during their execution, and the whole thing with full update entity removals clientside, since this code is running clientside.

I just don't think its worthwhile touching this code for minor (if any) performance improvement.

**Comment by Aws0mee** [comment]
> It technically might be marginally faster, but the biggest performance concern in this case would be iterating over all entities every frame, which is no longer the case.
> 
> The reliability concern comes with me not being sure the OnEntityCreated/Removed hooks having the correct class name during their execution, and the whole thing with full update entity removals clientside, since this code is running clientside.
> 
> I just don't think its worthwhile touching this code for minor (if any) performance improvement.

Fair enough, I might implement this on my own server and then send a PR only if I can be sure there's not issues.

**Pull request closed without merging**
